0 0 dataAuditErrors
263 0 4.1A.a/b, 4.1B: Active width >= 0.24um.
267 0 4.1C.a/b: Active spacing >= 0.28um.
277 0 4.1D.a: Nwell to N+ spacing >= 0.43um (1.8V).
284 0 4.1D.b: Nwell to N+ spacing >= 1.00um (3.3V).
293 0 4.1E: Nwell overlap N-tap >= 0.24um.
300 0 4.1F: Nwell to P-tap spacing >= 0.24um.
307 0 4.1G.a: Nwell overlap P+ Diffusion >= 0.43um (1.8V).
310 0 4.1G.b: Nwell overlap P+ Diffusion >= 1.00um (3.3V).
312 0 4A.1E/1F/1G Warning : Diffusion straddle N-Well
314 0 4.1H.a: Twell overlap N+ Diffusion >= 0.43um (1.8V).
317 0 4.1H.b: Twell overlap N+ Diffusion >= 1.00um (3.3V).
319 0 4.1I: Twell spacing N-tap in N-Well >= 0.24um.
322 0 4.1J: Twell overlap P-tap >= 0.24um.
324 0 4.1K.a: Twell to P+ spacing >= 0.43um (1.8V).
326 0 4.1K.b: Twell to P+ spacing >= 1.00um (3.3V).
340 0 welnotr_StampErrorFloat
341 0 welnotr_StampErrorMult
342 0 welnotr_StampErrorConnect
347 0 nwel3_StampErrorFloat
348 0 nwel3_StampErrorMult
349 0 nwel3_StampErrorConnect
358 0 4.2A.a: Minimum N-Well width is 0.9um
362 0 4.2A.b: Minimum width for N-Well resistor is 1.5um
364 0 4.2A.c Maximum width for N-Well resistor is 20um
368 0 4.2B.a: Minimum Equal Potential N-Well spacing is 0um or >= 0.9um
370 0 4.2B.b1: Minimum Non-Equal Potential 1.8V N-Well spacing is 1.5um
372 0 4.2B.b2: Minimum N-Well to N-Well spacing (non-equal-potential, 3.3V device) is 2um.
374 0 4.2B.c: Minimum N-Well resistor spacing is 2.2um
375 0 4.2C: N-Well Resistor overlap N-well is 0um.
377 0 4.2D: N-Well Resistor to N+ Diffusion (for N-Well tap) is 0um.
388 0 4.2C/D: The resistor marker layer edges must either be entirely coincident       with N-Well edge or at least partially butted to N+ Tap (terminal).
393 0 4.3A: Minimum T-Well width is 0.9um
398 0 4.3B.a: Minimum Equal Potential T-Well spacing is 0um or >= 0.9um
405 0 4.3B.b1: Minimum Non-Equal Potential 1.8V T-Well spacing is 1.5um
412 0 4.3B.b2: Minimum Non-Equal Potential 3.3V T-Well spacing is 2.0um
417 0 4.3C: Minimum N-Well overlap T-Well is 1.5um
418 0 4.3C: T-Well must be surrounded by N-Well.
424 0 4.4A: Minimum Poly width for PMOS is 0.24um
428 0 4.4B: Minimum VTPL width is 0.45um
430 0 4.4C: Minimum VTPL spacing is 0.45um
433 0 4.4D: Minimum VTPL overlap Diffusion on the diffusion of related device is 0.3um
435 0 4.4E: Minimum VTPL to unrelated Diffusion spacing is 0.3um
438 0 4.4F: Minimum VTPL overlap Poly of related device is 0.4um
440 0 4.4G: Minimum VTPL to unrelated Poly spacing (in diffusion region) is 0.4um
450 0 4.5A: Minimum Poly width for PMOS is 0.5um
454 0 4.5B: Minimum VTPHL width is 0.45um
456 0 4.5C: Minimum VTPHL spacing is 0.45um
459 0 4.5D: Minimum VTPHL overlap Diffusion on the diffusion of related device is 0.3um
461 0 4.5E: Minimum VTPHL to unrelated Diffusion spacing is 0.3um
464 0 4.5F: Minimum VTPHL overlap Poly of related device is 0.4um
466 0 4.5G: Minimum VTPHL to unrelated Poly spacing (in diffusion region) >= 0.4um
468 0  4.6A: Minimum spacing of N_WELL to P_WELL_BLOCK is 0.9um.
477 0 4.7A.a: Minimum Poly width for NMOS (1.8V device) is 0.24um
478 0 4.7A.b: Minimum Poly width for NMOS (3.3V device) is 0.5um
482 0 4.7B: Minimum VTNL width is 0.45um
484 0 4.7C: Minimum VTNL spacing is 0.3um
487 0 4.7D: Minimum VTNL overlap Diffusion on the diffusion of related device is 0.3um
489 0 4.7E: Minimum VTNL to unrelated Diffusion spacing is 0.3um
492 0 4.7F: Minimum VTNL overlap Poly of related device is 0.4um
494 0 4.7G: Minimum VTNL to unrelated Poly spacing (in diffusion region) is 0.4um
502 0 4.8A: Minimum Poly width for NMOS is 0.3um
506 0 4.8B: Minimum VTNI width is 0.45um
508 0 4.8C: Minimum VTNI spacing is 0.45um
511 0 4.8D: Minimum VTNI overlap Diffusion on the diffusion of related device is 0.3um
513 0 4.8E: Minimum VTNI to unrelated Diffusion spacing is 0.3um
516 0 4.8F: Minimum VTNI overlap Poly of related device is 0.4um
518 0 4.8G: Minimum VTNI to unrelated Poly spacing (in diffusion region) is 0.4um
528 0 4.9A: Minimum Poly width for NMOS is 0.5um
532 0 4.9B: Minimum VTNHL width is 0.45um
534 0 4.9C: Minimum VTNHL spacing is 0.45um
537 0 4.9D: Minimum VTNHL overlap Diffusion on the diffusion of related device is 0.3um
539 0 4.9E: Minimum VTNHL to unrelated Diffusion spacing is 0.3um
542 0 4.9F: Minimum VTNHL overlap Poly of related device is 0.4um
544 0 4.9G: Minimum VTNHL to unrelated Poly spacing is 0.4um
550 0 4.13A: Minimum TG width is 0.45um
554 0 4.13B: Minimum TG spacing is 0.45um
560 0 4.13C: Minimum TG overlap Diffusion on the diffusion of 3.3V device is 0.3um
564 0 4.13D: Minimum TG to unrelated Diffusion spacing is 0.3um
581 0 4.13E: Minimum TG overlap Poly of 3.3V device is 0.4um
598 0 4.13F: Minimum TG to unrelated Poly spacing is 0.4um
605 0 4.14A/B/C: Minimum  Poly width is 0.18um.
608 0 4.14A.b: Minimum Poly width for NMOS (3.3V device) is 0.34um
611 0 4.14B.b: Minimum Poly width for PMOS (3.3V device) is 0.34um
641 0 4.14D.a1: Minimum Poly to Poly spacing (on diffusion region without contact in the spacing, Poly width <= 0.24um) is 0.28um.
645 0 4.14D.a2: Minimum Poly to Poly spacing (on difffusion region without contact in the spacing, Poly width > 0.24um(either side)) is 0.32um.
650 0 4.14D.b1/b2: Gate Poly spacing over diffusion w/contact is 0.34um
656 0 4.14D.c: Field Poly spacing is 0.24um
674 0 4.14D.c2.2: Wide Long Field Poly (width > 0.24um, length > 1.00um) spacing is 0.28um
678 0 4.14E: Minimum Poly extension onto field region (end cap) is 0.22um
690 0 4.14F: Minimum Poly on field region to Diffusion spacing is 0.1um
704 0 4.14G: Minimum end cap Poly to related Diffusion spacing is 0.12um
722 0 4.14H: Minimum Poly gate to field edge spacing is 0.28um
727 0 4.14I.a: 1.8V bent gate width >= 0.20um.
732 0 4.14I.b: Minimum Poly width for 45 degree bent gate is 0.38um
747 0 4.14J: Poly 90 degree bent gate is not allowed.
749 0 4.14K: Maximum Poly overlap Diffusion area is 6400 um^2
762 0 4.14N: Minimum Poly bent gate on field region to Diffusion spacing is 0.2um
779 0 4.15A: Minimum HR width is 0.6um
781 0 4.15B: Minimum HR to HR spacing is 0.6um
783 0 4.15C: Minimum HR Poly width is 0.18um
785 0 4.15D: Minimum SAB width for HR Poly resistor (Defome HR Poly resistor length) is 1.0um
788 0 4.15E: Minimum HR mask overlap HR Poly resistor is 1.5um
791 0 4.15F: Minimum HR to unrelated Poly spacing is 2.0um
793 0 4.15G: Minimum N+imp layer to HR Poly spacing is 0.5um
796 0 4.15H: Minimum P+imp layer to HR Poly spacing is 0.5um
807 0 4.15I: Minimum SAB extension over HR Poly is 0.5um
809 0 4.15J: Minimum HR Poly contact to SAB spacing is 0.5um
810 0 4.15K: Minimum HR to unrelated diffusion spacing is 0.5um
812 0 4.15L: Minimum NWELL layer overlap HR Poly is 2.0um
813 0 4.15M: HR Poly resistor must be allocated inside N-Well.
819 0 4.15N: P+ implant overlap SAB is 0.2um
821 0 4.15O: Minimum P+ implant spacing to unrelated poly resistor is 0.4um
824 0 4.15P: Minimum P+ implant layer overlap HR poly is 0.3um (this is the same for non-salicide poly resistor)
826 0 Warning : Active without N+ or P+ implant overlap was found
833 0 4.16A: Minimum N+ implant width is 0.40um.
838 0 4.16B: Minimum N+ implant spacing is 0.40um.
849 0 4.16C.a: Minimum N+ implant overlap N+ Diffusion (inside P-Well or Twell) is 0.22um
853 0 4.16C.b: Minimum N+ implant overlap N+ Diffusion (inside N-Well) is 0.08um
857 0 4.16D.a: Minimum N+ implant to P+ Diffusion (inside N-Well) spacing is 0.22um
864 0 4.16D.b: Minimum N+ implant to P+ Diffusion (inside P-Well or Twell) spacing is 0.08um
866 0 4.17J/4.16J: Minimum N+/P+ implant extension over Poly to form N+/P+ S/D is 0.32um
868 0 4.16F/4.17F: Minimum N+ to P+ diffusion spacing in the same potential is 0um
871 0 4.16F,M/4.17F,M: Butting N+ to P+ Diffusions must be at the same potential (electrically connected).
874 0 4.16G/4.17H: Minimum N+ implant overlap Diffusion / Diffusion extension over P+ implant to form N+ region is 0.24um
876 0 4.17G/4.16H: Minimum P+ implant overlap Diffusion / Diffusion extension over N+ Implant to form P+ region is 0.24um
879 0 4.16I/4.17J: Minimum N+ implant to Poly spacing / P+ implant extension over Poly to form P+ S/D region is 0.32um
881 0 4.17I/4.16J: Minimum P+ implant to Poly spacing / N+ implant extension over Poly to form N+ S/D region is 0.32um
885 0 4.16K/4.17L: Minimum N+ implant overlap N+ contact / P+ implant to N+ contact spacing is 0.12um
903 0 4.16N: Maximum N+ Diffusion to the nearest P+ pick-up spacing (inside P-Well or Twell) is 20um (I/O, RAM, ROM, capacitor and diode are excepted)
910 0 4.17A: Minimum P+ implant width is 0.4um
915 0 4.17B: Minimum P+ implant spacing is 0.4um
919 0 4.17C.a: Minimum P+ implant overlap P+ Diffusion (inside N-Well) is 0.22um
929 0 4.17C.b: Minimum P+ implant overlap P+ Diffusion (inside P-Well or Twell) is 0.08um
936 0 4.17D.a: Minimum P+ implant to N+ Diffusion (inside P-Well or Twell) spacing is 0.22um
937 0 4.17D.b: Minimum P+ implant to N+ Diffusion (inside N-Well) spacing is 0.08um
942 0 4.16L/4.17K: Minimum P+ implant overlap P+ contact / Minimum N+ implant to P+ contact spacing is 0.12um
952 0 4.16M/17M: Soft Contacts are prohibited.
992 0 4.17N: Maximum P+ Diffusion to the nearest N+ pick-up spacing is 20um (I/O, RAM, ROM, capacitor and diode are excepted)
1010 0 4.18A: Minimum SAB width is 0.6um
1014 0 4.18B: Minimum SAB spacing is 0.6um
1015 0 4.18C: Non-salicide contact is not allowed.
1018 0 4.18E: Minimum distance of SAB edge to Diffusion edge is 0.3um
1021 0 4.18F: Minimum SAB extention over Diffusion is 0.3um.
1025 0 4.18G.a: Minimum SAB to Diffusion Contact spacing is 0.3um
1031 0 4.18G.b: Minimum SAB to Poly Contact spacing is 0.3um
1033 0 4.18H: Minimum SAB to unrelated Diffusion spacing is 0.24um
1035 0 4.18.I.b: Minimum SAB to Poly Contact spacing is 0.3um.
1050 0 4.18K: Minimum SAB extension over Diffusion non-salicide resistor is 0.38um
1056 0 4.18L: Minimum SAB extension over Poly non-salicide resistor is 0.38um
1066 0 4.18M: Minimum SAB to salicide contact spacing is 0.38um (include 4.18F.b)
1071 0 4.18N: Minimum P+ implant layer overlap P+ Poly non-salicide resistor is 0.3um
1073 0 4.18O: Minimum P+ implant layer to N+ Poly non-salicide resistor spacing is 0.3um
1078 0 4.18P: P+ Poly non-salicide resistor must be allocated inside N-Well. Minimum N-Well overlap P+ Poly non-salicide resistor is 0.3um
1082 0 4.18Q: N+ Poly non-salicide resistor must be allocated outside N-Well. Minimum N-Well to N+ Poly non-salicide resistor spacing is 0.3um
1087 0 4.18R: Minimum N+ implant layer overlap N+ Poly non-salicide resistor is 0.3um
1089 0 4.18S: Minimum N+ implant layer to P+ Poly non-salicide resistor spacing is 0.3um
1090 0 4.18T: Non-salicide contact for device or non-salicide resistor is not allowed.
1096 0 4.19A: Maximum and Minimum Contact size is 0.24 X 0.24um^2
1105 0 4.19B: Minimum Contact spacing is 0.26um
1114 0 4.19C.a: Minimum Diffusion Contact to Poly spacing (1.8V device) is 0.15um
1119 0 4.19C.b: Minimum Diffusion Contact to Poly spacing (3.3 device) is 0.3um
1126 0 4.19D: Minimum Poly Contact to Diffusion edge spacing is 0.18um
1139 0 4.19E: Minimum Poly overlap Contact is 0.1um
1150 0 4.19F: P+ Diffusion overlap Contact is 0.1um
1161 0 4.19G: N+ Diffusion overlap Contact is 0.1um
1163 0 4.19I: Poly contact on Diffusion is not allowed.
1170 0 4.20A: Minimum Metal1 width is 0.24um
1176 0 4.20B.a: Minimum Metal1 to Metal1 spacing (absolute minimum) is 0.24um
1186 0 4.20B.b: Minimum Metal1 to Metal1 spacing (for Metal1 width >= 10um) is 0.28um
1188 0 4.20D.a/d: Minimum Metal1 overlap contact is 0um
1199 0 4.20D.b/c/e: Minimum Metal1 must enclose the contact on two entire non-adjacent edges is 0.08um
1201 0 4.20E: Minimum Metal1 area is 0.1764 um^2
1205 0 4.21A: Maximum and Minimum Mvia1 size is 0.28 X 0.28um^2
1213 0 4.21B.a/b: Minimum Mvia1 to Mvia1 spacing is 0.28um
1214 0 4.21C.a: Minimum Metal1 overlap Mvia1 is 0um
1229 0 4.21C.b: Minimum wide Metal1 (>= 10.00um) overlap Mvia1 is 0.2um
1237 0 4.21C.c/d/e: Minimum Metal1 must enclose the Mvia1 on two entire non-adjacent edges is 0.08um
1243 0 4.22A: Minimum Metal2 width is 0.28um
1247 0 4.22B: Minimum Metal2 to Metal2 spacing (absolute minimum) is 0.28um
1257 0 4.22B.b: Minimum Metal2 to Metal2 spacing (for Metal2 width >= 10um) is 0.32um
1258 0 4.22D.a/d: Minimum Metal2 overlap Mvia1 is 0um
1264 0 4.22D.b/c/e: Minimum Metal2 must enclose the Mvia1 on two entire non-adjacent edges is 0.08um
1266 0 4.22E: Minimum Metal2 area is 0.1936 um^2
1270 0 4.23A: Maximum and Minimum Mvia2 size is 0.28 X 0.28um^2
1272 0 4.23B.a/b: Minimum Mvia2 to Mvia2 spacing is 0.28um
1273 0 4.23C.a: Minimum Metal2 overlap Mvia2 is 0um
1288 0 4.23C.b: Minimum wide Metal2 (>= 10.00um) overlap Mvia2 is 0.20um
1294 0 4.23C.c/d/e: Minimum Metal2 must enclose the Mvia2 on two entire non-adjacent edges is 0.08um
1298 0 4.24A: Minimum Metal3 width is 0.28um
1300 0 4.24B: Minimum Metal3 to Metal3 spacing (absolute minimum) is 0.28um
1310 0 4.24B.b: Minimum Metal3 to Metal3 spacing (for Metal3 width >= 10um) is 0.32um
1311 0 4.24D.a/d: Minimum Metal3 overlap Mvia2 >= 0um
1317 0 4.24D.b/c/e: Minimum Metal3 must enclose the Via2 on two entire non-adjacent edges is 0.08um
1319 0 4.24E: Minimum Metal3 area is 0.1936 um^2
1323 0 4.25A: Maximum and Minimum Mvia3 size is 0.28 X 0.28um^2
1325 0 4.25B.a/b: Minimum Mvia3 to Mvia3 spacing is 0.28um
1326 0 4.25C.a: Minimum Metal3 overlap Mvia3 is 0um
1341 0 4.25C.b: Minimum wide Metal3 (>= 10.00um) Overlap Mvia3 is 0.2um
1347 0 4.25C.c/d/e: Minimum Metal3 must enclose the Via3 on two entire non-adjacent edges is 0.08um
1351 0 4.26A: Minimum Metal4 width is 0.28um
1353 0 4.26B: Minimum Metal4 to Metal4 spacing (absolute minimum) is 0.28um
1363 0 4.26B.b: Minimum Metal4 to Metal4 spacing (for Metal4 width >= 10um) is 0.32um
1364 0 4.26D.a/d: Minimum Metal4 overlap Mvia3 is 0um
1370 0 4.26D.b/c/e: Minimum Metal4 must enclose the Via3 on two entire non-adjacent edges is 0.08um
1372 0 4.26E: Minimum Metal4 area is 0.1936 um^2
1376 0 4.27A: Maximum and Minimum Mvia4 size is 0.28 X 0.28um^2
1378 0 4.27B.a/b: Minimum Mvia4 to Mvia4 spacing is 0.28um
1379 0 4.27C.a: Minimum Metal4 overlap Mvia4 is 0um
1394 0 4.27C.b: Minimum wide Metal4 (>= 10um) Overlap Mvia4 is 0.2um
1400 0 4.27C.c/d/e: Minimum Metal4 must enclose the Via4 on two entire non-adjacent edges is 0.08um
1406 0 4.28A: Minimum Metal5 width is 0.28um
1408 0 4.28B: Minimum Metal5 to Metal5 spacing (absolute minimum) is 0.28um
1418 0 4.28B.b: Minimum Metal5 to Metal5 spacing (for Metal5 width >= 10um) is 0.32um
1419 0 4.28D.a/d: Minimum Metal5 overlap Mvia4 is 0um
1425 0 4.28D.b/c/e: Minimum Metal5 must enclose the Via4 on two entire non-adjacent edges is 0.08um
1427 0 4.28E: Minimum Metal5 area is 0.1936 um^2
1431 0 4.30A: Maximum and Minimum Mvia5 size is 0.28 X 0.28um^2
1433 0 4.30B.a/b: Minimum Mvia5 to Mvia5 spacing is 0.28um
1434 0 4.30C.a: Minimum Metal5 overlap MVia5 is 0um
1449 0 4.30C.b: Minimum wide Metal5 (>= 10um) Overlap MVia5 is 0.2um
1452 0 4.30C.c/d/e: Minimum Metal5 must enclose the Via5 on two entire non-adjacent edges is 0.08um
1459 0 4.29A: Minimum METAL_CAP width is 0.6um
1461 0 4.29B: Minimum METAL_CAP to METAL_CAP spacing is 0.55um
1467 0 4.29C: Minimum LSM overlap METAL_CAP Length is 0.5um
1469 0 4.29C: METAL_CAP layer must be within LSM area.
1472 0 4.29D: Minimum METAL_CAP overlap LMvia Length is 0.5um
1473 0 4.29D: METAL_CAP must overlap LMvia - straddle is not allowed.
1475 0 4.29E: Minimum Unrelated LMvia to METAL_CAP spacing is 0.5um
1477 0 4.29F: Maximum METAL_CAP overlap LSM area = 100um*100um.
1485 0 4.29G: The minimum overlap of M1 ground plate to LSM is 10um
1489 0 4.29H: Minimum overlap of P-Well block layer (block P-Well implant) to LSM is 10um
1490 0 4.29I:Outside MCAP : Minimum spacing of diffusion to MCAP is 1um
1493 0 4.29I_b: Inside MCAP : Minimum MCAP enclosure of DIFFUSION is 4um
1495 0 4.29I_c: Inside MCAP :  Minimum spacing of DIFFUSION to LSM is 4um
1496 0 4.29J: Minimum spacing of N_WELL to MCAP is 0um
1497 0 4.29K: Minimum spacing of POLY1 to MCAP is 0um
1498 0 4.29L: Minimum spacing of N+ to MCAP is 0um
1502 0 4.31A: Minimum Thick Top Metal width is 1.2um
1504 0 4.31B: Minimum Thick Top Metal to Top Metal spacing (absolute minimum) is 1.0um
1516 0 4.31B.b: Minimum Thick Top Metal to Top Metal spacing (for Top Metal width >= 10um) is 1.5um
1524 0 4.31C: Minimum Top Via must be enclosed by Thick Top Metal is 0.4um
1526 0 4.31D: Minimum Top Metal area is 9 um^2
1535 0 4.31H: The minimum overlap of IND to inductor layer is 10um
1540 0 4.31H: The minimum overlap of IND to inductor layer is 10um
1545 0 4.33A: Minimum PESD width is 0.6um
1547 0 4.33B: Minimum PESD spacing is 0.60um
1564 0 drc(DIFF (width < 0.14))
1568 0 drc(DIFF (width < 0.01) withCornerTouch fig)
1573 0 drc(DIFF (sep < 0.26))
1578 0 drc(DIFF (notch < 0.11))
1583 0 drc(NWEL ndiff1_ram (sep < 0.38))
1589 0 drc(NWEL pdiff1_ram (enc < 0.2))
1593 0 drc(PO1 (width < 0.08))
1597 0 drc(PO1 (width < 0.01) withCornerTouch fig)
1607 0 BDSP4.8D.b
1613 0 BDSP_4.8D.c1_1
1619 0 BDSP_4.8D.c1_2
1624 0 drc(blfpedg ((0 < sep) < 0.24))
1629 0 drc(blfpedg smfpedg ((0 < sep) < 0.24))
1635 0 drc(PO1 DIFF (enc < 0.01))
1638 0 BDSP4.8F
1645 0 BDSP_4.8G
1649 0 BDSP_4.8H
1651 0 BDSP_4.8J
1656 0 drc(bent_fpoly gate_diff_edge (sep < 0.02))
1662 0 drc(bent_fpoly gate_diff_edge (enc < 0.02))
1666 0 BDSP_4.17D.b
1671 0 drc(ctdiff1 PO1 (sep < 0.08))
1676 0 drc(ctfpol DIFF (sep < 0.17))
1682 0 drc(pact ctpdiff (enc < 0.03))
1688 0 drc(nact ctndiff (enc < 0.03))
1693 0 drc(ME1 (sepNotch < 0.23))
1701 0 BDSP_4.13D.bc
1706 0 BDSP_4.14C.c/d/e
1710 0 drc(DIFF (width < 0.07))
1714 0 drc(DIFF (width < 0.01) withCornerTouch fig)
1719 0 drc(DIFF (sep < 0.26))
1724 0 drc(DIFF (notch < 0.11))
1729 0 drc(NWEL ndiff1_ram (sep < 0.38))
1734 0 BLSP_4.1E
1740 0 drc(NWEL pdiff1_ram (enc < 0.2))
1744 0 drc(PO1 (width < 0.09))
1748 0 drc(PO1 (width < 0.01) withCornerTouch fig)
1753 0 BLSP_4.8D.a1
1758 0 BLSP_4.8D.a2
1764 0 BLSP_4.8D.b1
1771 0 BLSP_4.8D.c1_1
1778 0 BLSP_4.8D.c1_2
1786 0 BLSP_4.8D.c22
1792 0 drc(PO1 DIFF (enc < 0.02))
1797 0 BLSP_4.8G
1801 0 BLSP_4.8H
1809 0 BLSP_4.8N: Minimum bent field Poly to Diffusion spacing is 0.05um
1815 0 drc(NPLUS actpsub (enc < 0.15))
1820 0 drc(NPLUS actnwel (sep < 0.19))
1825 0 BLSP_4.10D.b
1829 0 drc(CONT (width < 0.05))
1833 0 drc(CONT (width < 0.01) withCornerTouch fig)
1838 0 drc(CONT (sep < 0.22))
1843 0 drc(CONT (notch < 0.1))
1849 0 drc(PO1 polcnt (enc < 0.031))
1853 0 drc(ME1 (width < 0.05))
1858 0 drc(ME1 (sepNotch < 0.16))
1862 0 drc(DIFF (width < 0.07))
1867 0 drc(DIFF (sep < 0.26))
1872 0 drc(DIFF (notch < 0.11))
1877 0 drc(NWEL ndiff1_ram (sep < 0.38))
1883 0 drc(NWEL pdiff1_ram (enc < 0.2))
1887 0 drc(PO1 (width < 0.09))
1893 0 BLSP1_4.8D.a1
1898 0 BLSP1_4.8D.a2
1902 0 BLSP1_4.8D.b1
1908 0 BLSP1_4.8D.c1_1
1914 0 BLSP1_4.8D.c1_2
1922 0 BLSP1_4.8D.c22
1930 0 BLSP1_4.8D.c22
1934 0 BLSP1_4.8E
1939 0 BLSP1_4.8F
1944 0 BLSP1_4.8G
1950 0 drc(DIFF gate ((0 < enc) < 0.02))
1955 0 drc(bent_fpoly gate_diff_edge (sep < 0.05))
1961 0 drc(bent_fpoly gate_diff_edge (enc < 0.05))
1967 0 drc(NPLUS actpsub (enc < 0.19))
1971 0 drc(CONT (width < 0.05))
1976 0 drc(CONT (sep < 0.22))
1981 0 drc(CONT (notch < 0.1))
1987 0 drc(PO1 ctfpol (enc < 0.05))
1993 0 drc(pact ctpdiff (enc < 0.01))
1999 0 drc(nact ctndiff (enc < 0.01))
2003 0 drc(ME1 (width < 0.05))
2008 0 drc(ME1 (sepNotch < 0.15))
2013 0 BLSP1_4.13D
2018 0 drc(NWEL ndiff1_ram (sep < 0.43))
2024 0 drc(NWEL pdiff1_ram (enc < 0.32))
2027 0 DP_4.8F
2036 0 DP_4.8G
2040 0 DP_4.9C.a
2046 0 drc(NPLUS actnwel ((0 < enc) < 0.04))
2050 0 DP_4.9D.b
2056 0 drc(PPLUS actpsub ((0 < enc) < 0.07))
2061 0 drc(PPLUS actpsub ((0 < sep) < 0.22))
2066 0 DP_4.10D.b
2072 0 drc(PO1 ctfpol (enc < 0.08))
2078 0 drc(pact ctpdiff (enc < 0.07))
2084 0 drc(nact ctndiff (enc < 0.07))
2088 0 drc(ME1 (width < 0.07))
2093 0 drc(ME1 (sep < 0.21))
2098 0 drc(ME1 (notch < 0.2))
2107 0 DP_4.13D
2111 0 drc(DIFF (width < 0.14))
2116 0 drc(DIFF (sep < 0.26))
2121 0 drc(DIFF (notch < 0.11))
2126 0 drc(NWEL ndiff1_ram (sep < 0.33))
2132 0 drc(NWEL pdiff1_ram (enc < 0.36))
2136 0 drc(PO1 (width < 0.08))
2142 0 DP1_4.8D.b1
2148 0 DP1_4.8D.c1
2154 0 drc(PO1 DIFF (enc < 0.03))
2159 0 drc(PO1 DIFF (sep < 0.07))
2166 0 DP1_4.8G
2170 0 DP1_4.8H
2172 0 DP1_4.8J
2177 0 drc(ctdiff1 PO1 (sep < 0.06))
2183 0 drc(pact ctpdiff (enc < 0.03))
2189 0 drc(nact ctndiff (enc < 0.03))
2193 0 drc(DIFF (width < 0.14))
2198 0 drc(DIFF (sep < 0.26))
2203 0 drc(DIFF (notch < 0.11))
2208 0 drc(NWEL ndiff1_ram (sep < 0.38))
2214 0 drc(NWEL pdiff1_ram (enc < 0.2))
2218 0 drc(PO1 (width < 0.08))
2224 0 DP2_4.8D.b1
2230 0 DP2_4.8D.c1.1
2236 0 DP2_4.8D.c1.2
2242 0 drc(PO1 DIFF (enc < 0.01))
2247 0 drc(PO1 DIFF (sep < 0.02))
2254 0 DP2_4.8G
2259 0 DP2_4.8H
2261 0 DP2_4.8J
2266 0 drc(bent_fpoly gate_diff_edge (sep < 0.02))
2272 0 drc(bent_fpoly gate_diff_edge (enc < 0.02))
2277 0 drc(ctdiff1 PO1 (sep < 0.08))
2282 0 drc(ctfpol DIFF (sep < 0.17))
2288 0 drc(pact ctpdiff (enc < 0.03))
2294 0 drc(nact ctndiff (enc < 0.03))
2299 0 DP2_4.13D
2304 0 DP2_4.14C.b
2309 0 drc(ctdiff1 PO1 (sep < 0.14))
2315 0 drc(pact ctpdiff (enc < 0.09))
2321 0 drc(nact ctndiff (enc < 0.09))
2325 0 drc(DIFF (width < 0.07))
2330 0 drc(DIFF (sep < 0.26))
2335 0 drc(DIFF (notch < 0.11))
2340 0 drc(NWEL ndiff1_ram (sep < 0.38))
2346 0 drc(NWEL pdiff1_ram (enc < 0.2))
2350 0 drc(PO1 (width < 0.09))
2355 0 BLSPLP_4.14D.a1
2359 0 BLSPLP_4.14D.a2
2364 0 BLSPLP_4.14D.b1
2370 0 BLSPLP_4.14D.c1_1
2376 0 BLSPLP_4.14D.c1_2
2390 0 BLSPLP_4.14D.c2.1a
2399 0 BLSPLP_4.14G
2404 0 drc(bent_fpoly gate_diff_edge (sep < 0.05))
2408 0 drc(NPLUS (width < 0.29))
2413 0 drc(NPLUS (sepNotch < 0.234))
2419 0 drc(NPLUS actpsub (enc < 0.2))
2424 0 drc(PPLUS (sepNotch < 0.235))
2429 0 drc(CONT (sep < 0.22))
2434 0 drc(CONT (notch < 0.1))
2440 0 drc(pact ctpdiff (enc < 0.01))
2446 0 drc(nact ctndiff (enc < 0.01))
2450 0 drc(ME1 (width < 0.05))
2455 0 drc(ME1 (sep < 0.13))
2460 0 BLSPLP_4.21C.c/d/e
